image: golang:1.8-alpine

variables:
  GO_PROJECT_PATH: '/go/src/git.dolansoft.org/$CI_PROJECT_PATH'

before_script:
  - echo $GO_PROJECT_PATH
  - apk update
  - apk add git
  - apk add protoc
  - go get github.com/tools/godep
  - mkdir -p $GO_PROJECT_PATH
  - rmdir $GO_PROJECT_PATH
  - cp -r $CI_PROJECT_DIR $GO_PROJECT_PATH
  - cd $GO_PROJECT_PATH

build-protos:
  stage: build
  script:
    - go get -u github.com/golang/protobuf/proto
    - go get -u github.com/golang/protobuf/protoc-gen-go
    - go get -u google.golang.org/grpc
    - mkdir pb
    - protoc *.proto --go_out=plugins=grpc:../pb

test:
  stage: test
  script:
    - godep restore
    - go test -v ./...
