image: golang:1.8-alpine

variables:
  GO_PROJECT_PATH: '/go/src/git.dolansoft.org/$CI_PROJECT_PATH'

before_script:
  - echo $GO_PROJECT_PATH
  - apk --update add git protobuf
  - go get github.com/tools/godep
  - mkdir -p $GO_PROJECT_PATH
  - rmdir $GO_PROJECT_PATH
  - cp -r $CI_PROJECT_DIR $GO_PROJECT_PATH
  - cd $GO_PROJECT_PATH
  - go get -u github.com/golang/protobuf/proto
  - go get -u github.com/golang/protobuf/protoc-gen-go
  - go get -u google.golang.org/grpc
  - mkdir pb
  - cd protos
  - protoc *.proto --go_out=plugins=grpc:../pb
  - cd ..

test:
  stage: test
  script:
    - godep restore
    - go test -v ./...
