image: golang:1.8-alpine

variables:
  GO_PROJECT_PATH: '/go/src/git.dolansoft.org/$CI_PROJECT_PATH'

before_script:
  - apk update
  - apk add git
  - go get github.com/tools/godep
  - mkdir -p $GO_PROJECT_PATH
  - cp -rT $CI_PROJECT_DIR $GO_PROJECT_PATH
  - cd $GO_PROJECT_PATH

test:
  stage: test
  script:
    - godep restore
    - go test -v ./...
